import { StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { layout, rhythm, spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

export const earningsStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: 'transparent' },
  center: {
    flex: 1,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: layout.screenPaddingH,
    gap: spacing[3],
  },
  errorTitle: {
    fontFamily: 'InstrumentSerif-Regular',
    fontSize: 28,
    color: colors.text,
    letterSpacing: 0,
  },
  errorBody: {
    fontFamily: 'Outfit-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  retryButton: {
    minHeight: 44,
    borderRadius: 22,
    paddingHorizontal: spacing[5],
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
  },
  retryButtonText: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 14,
    color: colors.background,
  },
  content: {
    paddingHorizontal: layout.screenPaddingH,
    paddingTop: rhythm.screenTop,
    paddingBottom: rhythm.tabClearance,
    gap: rhythm.sectionGap,
  },
  earningsHero: {
    borderRadius: layout.cardBorderRadius,
    padding: spacing[5],
    gap: spacing[2],
    backgroundColor: colors.surfaceLevel1,
    borderWidth: 1,
    borderColor: colors.border,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  heroTopInfo: {
    flex: 1,
    alignItems: 'flex-start',
    gap: 2,
  },
  heroLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 10,
    color: colors.textTertiary,
    letterSpacing: 0,
  },
  heroSub: {
    fontFamily: 'Outfit-Medium',
    fontSize: 12,
    color: colors.textSecondary,
  },
  heroScore: {
    minWidth: 64,
    alignItems: 'flex-end',
  },
  heroScoreValue: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 22,
    color: colors.text,
  },
  heroScoreLabel: {
    fontFamily: 'Outfit-Medium',
    fontSize: 11,
    color: colors.textTertiary,
  },
  heroValue: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 44,
    lineHeight: 50,
    letterSpacing: 0,
    color: colors.text,
  },
  heroSplits: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    gap: spacing[3],
  },
  heroTile: {
    flex: 1,
    backgroundColor: colors.surfaceLevel2,
    borderRadius: 12,
    paddingVertical: spacing[3],
    alignItems: 'center',
    gap: 2,
  },
  heroTileLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 9,
    color: colors.textTertiary,
    letterSpacing: 0,
  },
  heroTileValue: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 16,
    letterSpacing: 0,
  },
  scoreArena: {
    backgroundColor: colors.surfaceLevel1,
    borderRadius: layout.cardBorderRadiusLarge,
    borderWidth: 1,
    borderColor: colors.goldGlow,
    padding: spacing[4],
    gap: spacing[4],
    overflow: 'hidden',
  },
  scoreTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing[4],
  },
  scoreLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 11,
    color: colors.textSecondary,
    letterSpacing: 0,
  },
  scoreValue: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 62,
    lineHeight: 66,
    color: colors.text,
    letterSpacing: 0,
  },
  scoreCaption: {
    fontFamily: 'Outfit-Medium',
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  rankPill: {
    minHeight: 44,
    borderRadius: 22,
    paddingHorizontal: spacing[3],
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceLevel2,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  rankPillValue: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 15,
    color: colors.goldBright,
  },
  rankPillLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 9,
    color: colors.textTertiary,
    letterSpacing: 0,
  },
  scoreFacts: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing[3],
  },
  scoreFact: {
    flex: 1,
    gap: 2,
  },
  scoreFactValue: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 17,
    color: colors.text,
  },
  scoreFactLabel: {
    fontFamily: 'Outfit-Medium',
    fontSize: 11,
    lineHeight: 14,
    color: colors.textSecondary,
  },
  scoreDivider: {
    width: 1,
    height: 30,
    marginHorizontal: spacing[3],
    backgroundColor: colors.border,
  },
  scoreRules: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing[3],
  },
  scoreRulesLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 10,
    color: colors.textTertiary,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  scoreRulesText: {
    flex: 1,
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 12,
    color: colors.goldBright,
    textAlign: 'right',
  },
  section: { gap: spacing[2] },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontFamily: 'InstrumentSerif-Regular',
    fontSize: 22,
    color: colors.text,
    letterSpacing: 0,
  },
  sectionCount: {
    ...typography.caption,
    color: colors.textTertiary,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  darkCard: {
    backgroundColor: colors.surfaceLevel1,
    borderRadius: layout.cardBorderRadius,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  darkCardBody: { padding: spacing[4] },
  payoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  rowLast: { borderBottomWidth: 0 },
  payoutMeta: { flex: 1, gap: 2 },
  payoutName: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 14,
    color: colors.text,
  },
  payoutSub: {
    fontFamily: 'Outfit-Medium',
    fontSize: 12,
    color: colors.textSecondary,
  },
  payoutRight: { alignItems: 'flex-end', gap: 2 },
  payoutAmount: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 14,
    color: colors.success,
  },
  payoutDate: {
    fontFamily: 'JetBrainsMono-Regular',
    fontSize: 11,
    color: colors.textTertiary,
  },
  emptyText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  lbRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardSurfaceDivider,
  },
  lbRowYou: {
    backgroundColor: 'rgba(212, 167, 68, 0.14)',
    borderBottomWidth: 0,
  },
  lbRank: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 14,
    color: '#B07A1A',
    width: 30,
    textAlign: 'center',
  },
  lbMeta: { flex: 1, gap: 2 },
  lbName: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 14,
    color: colors.cardSurfaceText,
  },
  lbCompany: {
    fontFamily: 'Outfit-Medium',
    fontSize: 12,
    color: colors.cardSurfaceTextMuted,
  },
  lbRight: { alignItems: 'flex-end', gap: 2 },
  lbScore: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 14,
    color: colors.cardSurfaceText,
  },
  creamCard: {
    backgroundColor: colors.cardSurface,
    borderRadius: layout.cardBorderRadius,
    overflow: 'hidden',
  },
  leaderboardEmpty: {
    fontFamily: 'Outfit-Medium',
    fontSize: 13,
    lineHeight: 19,
    color: colors.cardSurfaceTextMuted,
    padding: spacing[4],
  },
  creamSheen: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: layout.cardBorderRadius,
  },
});
