import { StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { layout, spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

export const earningsScreenStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: 'transparent' },
  center: {
    flex: 1,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    padding: layout.screenPaddingH,
    paddingTop: spacing[6],
    paddingBottom: 116,
    gap: spacing[6],
  },
  earningsHero: {
    borderRadius: layout.cardBorderRadiusLarge,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    overflow: 'hidden',
    gap: spacing[2],
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.30,
    shadowRadius: 20,
    elevation: 14,
  },
  heroGoldFill: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: layout.cardBorderRadiusLarge,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  heroOrbWrap: {
    marginRight: -spacing[1],
    marginVertical: -spacing[1],
  },
  heroTopInfo: {
    flex: 1,
    alignItems: 'flex-start',
    gap: 2,
  },
  heroLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 10,
    color: 'rgba(0, 0, 0, 0.65)',
    letterSpacing: 2.4,
  },
  heroSub: {
    fontFamily: 'Outfit-Medium',
    fontSize: 12,
    color: 'rgba(0, 0, 0, 0.62)',
  },
  heroValue: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 44,
    lineHeight: 50,
    letterSpacing: 0,
    color: '#000000',
  },
  heroSplits: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    gap: spacing[3],
  },
  heroTile: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.10)',
    borderRadius: 12,
    paddingVertical: spacing[3],
    alignItems: 'center',
    gap: 2,
  },
  heroTileLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 9,
    color: 'rgba(0, 0, 0, 0.55)',
    letterSpacing: 1.0,
  },
  heroTileValue: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 16,
    letterSpacing: 0,
  },
  materialSheen: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: layout.cardBorderRadiusLarge,
  },
  bevelTop: {
    position: 'absolute',
    top: 0,
    left: 24,
    right: 24,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.55)',
  },
  bevelBottom: {
    position: 'absolute',
    bottom: 0,
    left: 24,
    right: 24,
    height: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.22)',
  },
  section: { gap: spacing[2] },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  sectionTitle: {
    fontFamily: 'InstrumentSerif-Regular',
    fontSize: 22,
    color: colors.text,
    letterSpacing: 0,
  },
  sectionCount: {
    ...typography.caption,
    color: colors.textTertiary,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  payoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  payoutRowLast: { borderBottomWidth: 0 },
  payoutMeta: { flex: 1, gap: 2 },
  payoutName: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 14,
    color: colors.text,
  },
  payoutSub: {
    fontFamily: 'Outfit-Medium',
    fontSize: 12,
    color: colors.textSecondary,
  },
  payoutRight: { alignItems: 'flex-end', gap: 2 },
  payoutAmount: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 14,
    color: colors.success,
  },
  payoutDate: {
    fontFamily: 'JetBrainsMono-Regular',
    fontSize: 11,
    color: colors.textTertiary,
  },
  emptyText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  lbRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  lbRowLast: { borderBottomWidth: 0 },
  lbRowYou: {
    backgroundColor: colors.goldGlow,
  },
  lbRank: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 13,
    color: colors.goldBright,
    width: 28,
    textAlign: 'center',
  },
  lbMeta: { flex: 1, gap: 2 },
  lbName: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 14,
    color: colors.text,
  },
  lbCompany: {
    fontFamily: 'Outfit-Medium',
    fontSize: 12,
    color: colors.textSecondary,
  },
  lbRight: { alignItems: 'flex-end', gap: 2 },
  lbScore: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 14,
    color: colors.text,
  },
  lbHires: {
    fontFamily: 'JetBrainsMono-Regular',
    fontSize: 11,
    color: colors.textTertiary,
  },
  leaderboardEmpty: {
    fontFamily: 'Outfit-Regular',
    fontSize: 13,
    lineHeight: 19,
    color: colors.textSecondary,
    padding: spacing[4],
  },
  glassCard: {
    backgroundColor: colors.surfaceLevel1,
    borderRadius: layout.cardBorderRadius,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  glassCardBody: {
    padding: spacing[4],
  },
});
