import { StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { layout, rhythm, spacing } from '../../theme/spacing';
import { fontFamilies, typography } from '../../theme/typography';

export const profileStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: 'transparent' },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    paddingHorizontal: layout.screenPaddingH,
    paddingTop: spacing[4],
    paddingBottom: rhythm.tabClearance + spacing[4],
    gap: spacing[3],
  },
  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing[2],
  },
  pageHeaderCopy: {
    flex: 1,
    gap: spacing[0.5],
  },
  eyebrow: {
    ...typography.sectionEyebrow,
    color: colors.goldBright,
  },
  pageTitle: {
    ...typography.screenTitle,
    color: colors.text,
  },
  hero: {
    padding: spacing[4],
    gap: spacing[4],
    borderRadius: 24,
    backgroundColor: colors.profileCardSurface,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.24,
    shadowRadius: 20,
    elevation: 10,
  },
  profileCardSurface: {
    ...StyleSheet.absoluteFillObject,
  },
  profileCardGlow: {
    ...StyleSheet.absoluteFillObject,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing[3],
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
    gap: spacing[1],
    paddingTop: spacing[0.5],
  },
  displayName: {
    fontFamily: fontFamilies.bodySemiBold,
    fontSize: 24,
    lineHeight: 30,
    letterSpacing: 0,
    color: colors.text,
  },
  identityLine: {
    fontFamily: fontFamilies.body,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    color: colors.tagBlueText,
  },
  roleBadge: {
    alignSelf: 'flex-start',
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    paddingHorizontal: spacing[2],
    borderRadius: 12,
    backgroundColor: colors.gold,
  },
  roleBadgeText: {
    ...typography.sectionEyebrow,
    color: colors.navyDeep,
  },
  snapshot: {
    gap: spacing[3],
    paddingTop: 0,
    borderTopWidth: 0,
  },
  heroScore: {
    width: 86,
    minHeight: 64,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  scoreBlock: {
    alignItems: 'flex-end',
    gap: spacing[0.5],
  },
  scoreLabel: {
    ...typography.sectionEyebrow,
    maxWidth: 86,
    fontSize: 9,
    lineHeight: 12,
    color: colors.tagBlueText,
    textAlign: 'right',
  },
  scoreValue: {
    fontFamily: fontFamilies.monoMedium,
    fontSize: 40,
    lineHeight: 44,
    color: colors.goldBright,
    letterSpacing: 0,
    textAlign: 'right',
  },
  seekerHeadline: {
    ...typography.bodyLarge,
    color: colors.text,
  },
  metricRow: {
    flexDirection: 'row',
    gap: spacing[2],
  },
  metric: {
    flex: 1,
    minHeight: 58,
    justifyContent: 'center',
    gap: spacing[0.5],
    paddingHorizontal: spacing[3],
    borderRadius: 14,
    backgroundColor: colors.profileCardInset,
    borderWidth: 0,
    overflow: 'hidden',
  },
  metricValue: {
    ...typography.statMedium,
    color: colors.text,
  },
  metricLabel: {
    ...typography.sectionEyebrow,
    color: colors.textSecondary,
  },
  section: {
    gap: spacing[2.5],
    padding: spacing[4],
    borderRadius: 18,
    backgroundColor: colors.profileCardSurface,
    borderWidth: 0,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  sectionTitle: {
    ...typography.sectionTitle,
    color: colors.text,
  },
  sectionBody: {
    gap: spacing[2],
  },
  settingsRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2.5],
    borderRadius: 16,
    backgroundColor: colors.profileCardInset,
    borderWidth: 0,
    overflow: 'hidden',
  },
  rowIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: colors.goldGlow,
  },
  settingsLabel: {
    flex: 0.8,
    ...typography.rowTitle,
    color: colors.text,
  },
  settingsValue: {
    flex: 1,
    ...typography.rowMeta,
    color: colors.tagBlueText,
    textAlign: 'right',
  },
  settingsToggleValue: {
    flex: 1.2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing[2],
  },
  chipGroup: {
    gap: spacing[2],
  },
  chipGroupTitle: {
    ...typography.rowTitle,
    color: colors.text,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
  },
  chip: {
    maxWidth: '100%',
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1.5],
    borderRadius: 14,
    backgroundColor: colors.profileCardInset,
    borderWidth: 0,
    overflow: 'hidden',
  },
  chipText: {
    ...typography.chipLabel,
    color: colors.textSecondary,
  },
  emptyText: {
    ...typography.rowMeta,
    color: colors.textTertiary,
  },
  actionRow: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[3],
    borderRadius: 16,
    backgroundColor: colors.profileCardInset,
    borderWidth: 0,
    overflow: 'hidden',
  },
  actionCopy: {
    flex: 1,
    gap: spacing[0.5],
  },
  actionLabel: {
    ...typography.rowCaption,
    color: colors.textTertiary,
  },
  actionValue: {
    ...typography.rowTitle,
    color: colors.text,
  },
  signOutBtn: {
    marginTop: spacing[1],
  },
});
