import { StyleSheet } from 'react-native';

import { colors } from '../../../theme/colors';
import { DISCOVER_CARD_HEIGHT, discoverCardLayout } from './discoverCardLayout';

export const styles = StyleSheet.create({
  cardWrapper: {
    position: 'absolute',
    left: discoverCardLayout.inset,
    right: discoverCardLayout.inset,
    top: 0,
    height: DISCOVER_CARD_HEIGHT,
  },
  cardInner: { flex: 1 },
  ambientShadow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000',
    borderRadius: discoverCardLayout.radius,
    opacity: 0.50,
    transform: [{ translateY: 28 }],
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 30 },
    shadowOpacity: 0.6,
    shadowRadius: 44,
  },
  surface: {
    flex: 1,
    borderRadius: discoverCardLayout.radius,
    overflow: 'hidden',
    backgroundColor: colors.cardSurface,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.30,
    shadowRadius: 22,
    elevation: 14,
  },
  tapArea: { flex: 1 },
  materialSheen: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: discoverCardLayout.radius,
  },
  reactiveGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: discoverCardLayout.radius,
    zIndex: 4,
  },
  fullMediaCard: {
    flex: 1,
    backgroundColor: colors.navy,
  },
  officeImage: {
    width: '100%',
    height: '100%',
  },
  officeFallback: { ...StyleSheet.absoluteFillObject },
  bottomScrim: { ...StyleSheet.absoluteFillObject },
  overlayContent: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: discoverCardLayout.overlayPaddingHorizontal,
    paddingBottom: discoverCardLayout.overlayPaddingBottom,
    gap: discoverCardLayout.overlayGap,
  },
  overlayTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: discoverCardLayout.titleRowGap,
  },
  companyTitle: {
    flex: 1,
    fontFamily: 'InstrumentSerif-Regular',
    fontSize: 36,
    lineHeight: 40,
    color: colors.cream,
    textShadowColor: 'rgba(0, 0, 0, 0.45)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  verifiedChip: {
    minWidth: 88,
    height: discoverCardLayout.chipHeight,
    borderRadius: discoverCardLayout.chipRadius,
    borderWidth: 1,
    borderColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: discoverCardLayout.chipPaddingHorizontal,
    backgroundColor: 'rgba(3, 7, 18, 0.42)',
  },
  verifiedChipText: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 11,
    letterSpacing: 0.9,
    color: colors.goldBright,
  },
  companyRole: {
    fontFamily: 'Outfit-Medium',
    fontSize: 16,
    lineHeight: 21,
    color: 'rgba(245, 241, 232, 0.78)',
  },
  endorserProofRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 2,
  },
  endorserProofText: {
    flex: 1,
    fontFamily: 'Outfit-Medium',
    fontSize: 15,
    lineHeight: 20,
    color: 'rgba(245, 241, 232, 0.82)',
  },
  endorserMetaLine: {
    fontFamily: 'Outfit-Regular',
    fontSize: 15,
    lineHeight: 20,
    color: 'rgba(245, 241, 232, 0.72)',
  },
  stackPlate: {
    flex: 1,
    backgroundColor: colors.backgroundElevated,
  },
  clipMount: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -14,
    alignItems: 'center',
  },
  undoCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backgroundElevated,
    borderWidth: 1,
    borderColor: colors.goldDim,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.30,
    shadowRadius: 8,
    elevation: 4,
  },
  undoCirclePressed: {
    opacity: 0.85,
    transform: [{ scale: 0.94 }],
  },
});
