import { StyleSheet } from 'react-native';

import { colors } from '../../../theme/colors';

export const styles = StyleSheet.create({
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7, 12, 28, 0.85)',
  },
  surface: {
    backgroundColor: colors.cardSurface,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.5,
    shadowRadius: 40,
    elevation: 24,
  },
  scroll: { paddingBottom: 0 },
  heroImageZone: {
    width: '100%',
    aspectRatio: 1.12,
    backgroundColor: '#0A1F44',
    overflow: 'hidden',
  },
  heroImageFallback: { ...StyleSheet.absoluteFillObject },
  heroImage: { width: '100%', height: '100%' },
  heroImageShade: { ...StyleSheet.absoluteFillObject },
  summaryPanel: {
    marginTop: -42,
    marginHorizontal: 14,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: colors.navyDeep,
    paddingHorizontal: 28,
    paddingTop: 26,
    paddingBottom: 22,
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(245, 241, 232, 0.08)',
  },
  heroTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  companyTitle: {
    flex: 1,
    fontFamily: 'InstrumentSerif-Regular',
    fontSize: 40,
    lineHeight: 45,
    color: colors.cream,
    textShadowColor: 'rgba(0, 0, 0, 0.45)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  verifiedChip: {
    minWidth: 96,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(3, 7, 18, 0.42)',
  },
  verifiedChipText: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 12,
    letterSpacing: 0.9,
    color: colors.goldBright,
  },
  companyRole: {
    fontFamily: 'InstrumentSerif-Regular',
    fontSize: 30,
    lineHeight: 35,
    color: colors.cream,
  },
  endorserProofRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 4,
  },
  endorserProofText: {
    flex: 1,
    fontFamily: 'Outfit-Medium',
    fontSize: 15,
    lineHeight: 20,
    color: 'rgba(245, 241, 232, 0.82)',
  },
  endorserMetaLine: {
    fontFamily: 'Outfit-Regular',
    fontSize: 16,
    lineHeight: 21,
    color: 'rgba(245, 241, 232, 0.76)',
  },
  grabberRow: {
    position: 'absolute',
    top: 14,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 5,
  },
  grabber: {
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(245, 241, 232, 0.55)',
  },
  creamZone: { flex: 1 },
  section: {
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 18,
    gap: 12,
  },
  sectionLabel: {
    fontFamily: 'Outfit-Bold',
    fontSize: 10,
    color: 'rgba(0, 0, 0, 0.50)',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  extras: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
  },
  about: {
    fontFamily: 'Outfit-Regular',
    fontSize: 15,
    color: '#000000',
    lineHeight: 24,
  },
  skillsExtras: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  skillExtraChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
  },
  skillExtraText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 13,
    color: '#000000',
  },
  closeWrap: { position: 'absolute', top: 56, right: 18 },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.30)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
