import { StyleSheet } from 'react-native';

import { colors } from '../theme/colors';
import { layout, rhythm, spacing } from '../theme/spacing';

export const chatProfileStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  nav: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: layout.screenPaddingH,
  },
  navTitle: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 18,
    color: colors.text,
    letterSpacing: 0,
  },
  navSide: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    paddingHorizontal: layout.screenPaddingH,
    paddingBottom: rhythm.tabClearance,
  },
  hero: {
    alignItems: 'center',
    paddingTop: rhythm.sectionGap,
    paddingBottom: rhythm.sectionGap,
    gap: spacing[2],
  },
  name: {
    marginTop: spacing[2],
    fontFamily: 'Outfit-Bold',
    fontSize: 34,
    color: colors.text,
    letterSpacing: 0,
    textAlign: 'center',
  },
  subtitle: {
    fontFamily: 'Outfit-Regular',
    fontSize: 16,
    lineHeight: 22,
    color: colors.textSecondary,
    letterSpacing: 0,
    textAlign: 'center',
  },
  actionGrid: {
    flexDirection: 'row',
    gap: spacing[3],
    marginBottom: rhythm.sectionGap,
  },
  actionTile: {
    flex: 1,
    minHeight: 90,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[2],
    borderRadius: 18,
    backgroundColor: colors.surfaceLevel1,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionTilePrimary: {
    backgroundColor: colors.accentLight,
    borderColor: colors.accentDim,
  },
  actionTileDisabled: { opacity: 0.45 },
  actionText: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 14,
    color: colors.text,
    letterSpacing: 0,
    textAlign: 'center',
  },
  actionTextPrimary: { color: colors.accent },
  section: {
    marginBottom: rhythm.sectionGap,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: colors.surfaceLevel1,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionHeader: {
    paddingHorizontal: spacing[4],
    paddingTop: spacing[4],
    paddingBottom: spacing[2],
  },
  sectionTitle: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 11,
    color: colors.textTertiary,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  row: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingHorizontal: spacing[4],
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  rowBody: { flex: 1 },
  rowLabel: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 15,
    color: colors.text,
    letterSpacing: 0,
  },
  rowValue: {
    marginTop: spacing[0.5],
    fontFamily: 'Outfit-Regular',
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
    letterSpacing: 0,
  },
  rowMeta: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 12,
    color: colors.textSecondary,
    letterSpacing: 0,
  },
  readinessTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing[3],
    paddingHorizontal: spacing[4],
    paddingBottom: spacing[4],
  },
  readinessCopy: { flex: 1 },
  statusTitle: {
    fontFamily: 'Outfit-Bold',
    fontSize: 22,
    color: colors.text,
    letterSpacing: 0,
  },
  statusDetail: {
    marginTop: spacing[1],
    fontFamily: 'Outfit-Regular',
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
    letterSpacing: 0,
  },
  statusPill: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    paddingHorizontal: spacing[3],
    borderRadius: 999,
    borderWidth: 1,
  },
  statusPillText: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 12,
    letterSpacing: 0,
  },
  rail: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing[4],
    paddingBottom: spacing[4],
  },
  dot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  connector: {
    flex: 1,
    height: 1,
    opacity: 0.8,
  },
  loadingRow: {
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
