import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { ReactElement } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { lightJourney } from '../theme/lightJourney';
import type { EndorserAccountState } from './endorserAccount/endorserAccountModel';

type Props={state:EndorserAccountState};
type Item={title:string;detail:string;route?:string;danger?:boolean};
function Header():ReactElement{return <View style={s.header}><Pressable accessibilityLabel="Back" accessibilityRole="button" onPress={()=>router.back()} style={s.icon}><Ionicons color={lightJourney.ink} name="arrow-back" size={22}/></Pressable><Text style={s.wordmark}>Endorsly</Text><View style={s.icon}><Ionicons color={lightJourney.ink} name="shield-checkmark-outline" size={21}/></View></View>}
function Row({detail,danger,route,title}:Item):ReactElement{const body=<><View style={s.flex}><Text style={[s.rowTitle,danger&&s.danger]}>{title}</Text><Text style={[s.detail,danger&&s.danger]}>{detail}</Text></View>{route?<Ionicons color={lightJourney.textMuted} name="chevron-forward" size={18}/>:null}</>;return route?<Pressable accessibilityLabel={title} accessibilityRole="button" onPress={()=>router.push(route as never)} style={s.row}>{body}</Pressable>:<View style={s.row}>{body}</View>}
function Card({children}:{children:ReactElement|ReactElement[]}):ReactElement{return <View style={s.card}>{children}</View>}
function Earnings({state}:Props):ReactElement{if(state==='reward-detail'||state==='payout'||state==='paid')return <Reward state={state}/>;return <Page title="Your earnings" subtitle="Referral rewards are confirmed after successful joining."><View style={s.balance}><Text style={s.balanceLabel}>Available to withdraw</Text><Text style={s.balanceValue}>₹22,000</Text><Text style={s.detail}>1 confirmed referral reward</Text></View><Text style={s.section}>Reward activity</Text><Card><Row detail="Priya Nair · Senior Product Manager" route="/endorser/earnings/priya-razo" title="₹22,000 pending release"/><Row detail="Neha Kulkarni · UX Designer" title="₹22,000 paid"/></Card></Page>}
function Reward({state}:Props):ReactElement{const paid=state==='paid';const payout=state==='payout';const title=paid?'Reward paid':payout?'Payout scheduled':'Referral reward';const subtitle=paid?'₹22,000 was paid to your verified account.':payout?'₹22,000 is scheduled for 10 Aug 2026.':'Priya completed her successful joining verification.';return <Page title={title} subtitle={subtitle}><View style={s.rewardIcon}><Ionicons color={lightJourney.green} name={paid?'checkmark':'cash-outline'} size={34}/></View><Card><Row detail="Senior Product Manager · Razorpay" title="Priya Nair"/><Row detail="Confirmed after successful joining" title="Reward amount"/><Text style={s.amount}>₹22,000</Text></Card><Pressable accessibilityLabel={paid?'View earnings':payout?'View payout':'Schedule payout'} accessibilityRole="button" onPress={()=>router.push((paid?'/endorser/earnings':payout?'/endorser/earnings/priya-razo/paid':'/endorser/earnings/priya-razo/payout') as never)} style={s.primary}><Text style={s.primaryText}>{paid?'View earnings':payout?'View payout':'Schedule payout'}</Text></Pressable></Page>}
function Profile({state}:Props):ReactElement{const title=state==='preferences'?'Referral preferences':state==='payouts'?'Payout settings':state==='privacy'?'Privacy & account':'Arjun Menon';const subtitle=state==='profile'?'Product Manager at Razorpay · Work verified':'Manage your Endorsly account.';const rows:Item[]=state==='profile'?[{title:'Referral preferences',detail:'Roles, scope and availability',route:'/endorser/profile/preferences'},{title:'Payout settings',detail:'Bank account and tax details',route:'/endorser/profile/payouts'},{title:'Privacy & account',detail:'Data, security and support',route:'/endorser/profile/privacy'}]:state==='preferences'?[{title:'Product referrals',detail:'Product Management, Strategy'},{title:'Referral capacity',detail:'Up to 3 active referrals'},{title:'Typical reply time',detail:'Within 24 hours'}]:state==='payouts'?[{title:'Bank account',detail:'Verified · HDFC •••• 4281'},{title:'Tax information',detail:'PAN verified'},{title:'Payout frequency',detail:'After joining verification'}]:[{title:'Security',detail:'Password and two-step verification'},{title:'Download my data',detail:'Export your account data'},{title:'Help & support',detail:'FAQs and contact support'},{title:'Sign out',detail:'End current session',danger:true},{title:'Delete account',detail:'Permanent and irreversible',danger:true}];return <Page title={title} subtitle={subtitle}><Card>{rows.map(row=><Row key={row.title}{...row}/>)}</Card></Page>}
function Page({children,subtitle,title}:{children:ReactElement|ReactElement[];subtitle:string;title:string}):ReactElement{return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text accessibilityRole="header" style={s.title}>{title}</Text><Text style={s.subtitle}>{subtitle}</Text>{children}</ScrollView>}
function Content({state}:Props):ReactElement{return ['earnings','reward-detail','payout','paid'].includes(state)?<Earnings state={state}/>:<Profile state={state}/>}
export function EndorserAccountScreen({state}:Props):ReactElement{return <SafeAreaView edges={['top','left','right']} style={s.safe}><Header/><Content state={state}/></SafeAreaView>}
const s=StyleSheet.create({safe:{backgroundColor:lightJourney.background,flex:1},header:{alignItems:'center',flexDirection:'row',height:56,justifyContent:'space-between',paddingHorizontal:18},icon:{alignItems:'center',height:44,justifyContent:'center',width:44},wordmark:{color:lightJourney.ink,fontFamily:'IBMPlexSerif-Medium',fontSize:27},content:{flexGrow:1,padding:20},title:{color:lightJourney.ink,fontFamily:'IBMPlexSerif-Medium',fontSize:28,lineHeight:34,marginTop:8},subtitle:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:11,lineHeight:17,marginTop:4},balance:{backgroundColor:lightJourney.greenSoft,borderColor:lightJourney.border,borderRadius:12,borderWidth:1,marginTop:20,padding:17},balanceLabel:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:11},balanceValue:{color:lightJourney.ink,fontFamily:'GeistMono-Medium',fontSize:32,marginTop:5},section:{color:lightJourney.ink,fontFamily:'TikTokSans-Medium',fontSize:12,marginTop:22},card:{backgroundColor:lightJourney.surface,borderColor:lightJourney.border,borderRadius:11,borderWidth:1,marginTop:10,overflow:'hidden'},row:{alignItems:'center',borderBottomColor:lightJourney.border,borderBottomWidth:1,flexDirection:'row',justifyContent:'space-between',minHeight:66,paddingHorizontal:13},flex:{flex:1},rowTitle:{color:lightJourney.text,fontFamily:'TikTokSans-Medium',fontSize:12},detail:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:10,lineHeight:15,marginTop:3},danger:{color:lightJourney.error},rewardIcon:{alignItems:'center',alignSelf:'center',backgroundColor:lightJourney.greenSoft,borderColor:lightJourney.green,borderRadius:37,borderWidth:2,height:74,justifyContent:'center',marginTop:22,width:74},amount:{color:lightJourney.green,fontFamily:'GeistMono-Medium',fontSize:29,margin:13},primary:{alignItems:'center',backgroundColor:lightJourney.blue,borderRadius:14,height:52,justifyContent:'center',marginTop:20},primaryText:{color:'#FFFFFF',fontFamily:'TikTokSans-Semibold',fontSize:15}});
