import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { ReactElement } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { lightJourney } from '../theme/lightJourney';
import { nextEndorserReferralRoute, type EndorserReferralState } from './endorserReferral/endorserReferralModel';

type Props = { state: EndorserReferralState };

function Header(): ReactElement { return <View style={s.header}><Pressable accessibilityLabel="Back" accessibilityRole="button" onPress={() => router.back()} style={s.icon}><Ionicons color={lightJourney.ink} name="arrow-back" size={22} /></Pressable><Text style={s.wordmark}>Endorsly</Text><View style={s.icon}><Ionicons color={lightJourney.ink} name="shield-checkmark-outline" size={21} /></View></View>; }
function Button({ label, state }: { label: string; state: EndorserReferralState }): ReactElement { return <Pressable accessibilityLabel={label} accessibilityRole="button" onPress={() => router.push(nextEndorserReferralRoute(state) as never)} style={s.primary}><Text style={s.primaryText}>{label}</Text></Pressable>; }
function Card({ children }: { children: ReactElement | ReactElement[] }): ReactElement { return <View style={s.card}>{children}</View>; }
function Row({ icon, label, value, status }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string; status?: string }): ReactElement { return <View style={s.row}><Ionicons color={lightJourney.ink} name={icon} size={22} /><View style={s.flex}><Text style={s.label}>{label}</Text><Text style={s.detail}>{value}</Text></View>{status ? <Text style={status === 'Verified' ? s.verified : s.pending}>{status}</Text> : null}</View>; }

function Details(): ReactElement { return <Page title="Priya’s verified details" subtitle="Review the information Priya has approved for her referral."><Card><Row icon="document-text-outline" label="Resume" status="Verified" value="Priya_Nair_Resume_v3.pdf" /><Row icon="call-outline" label="Phone number" status="Verified" value="+91 98765 43210" /><Row icon="mail-outline" label="Email" status="Verified" value="priya.nair@cred.com" /><Row icon="logo-linkedin" label="LinkedIn" status="Verified" value="Permission to share profile" /></Card><Card><Row icon="lock-closed-outline" label="Consent" status="Awaiting" value="Priya controls what is shared" /></Card><Button label="Request package" state="details" /></Page>; }
function Received(): ReactElement { return <Page title="Priya’s package is ready" subtitle="All verified details were shared securely with you."><View style={s.success}><Ionicons color={lightJourney.green} name="shield-checkmark-outline" size={38} /></View><Card><Row icon="document-text-outline" label="Resume" status="Verified" value="Priya_Nair_Resume_v3.pdf" /><Row icon="briefcase-outline" label="Work" status="Verified" value="CRED · Senior Product Manager" /><Row icon="school-outline" label="Education" status="Verified" value="IIT Bombay" /></Card><Button label="Start referral" state="received" /></Page>; }
function Role(): ReactElement { return <Page title="Refer Priya to Razorpay" subtitle="Choose the opportunity that best fits her profile."><Card><Row icon="briefcase-outline" label="Senior Product Manager" value="Razorpay · Bengaluru · Hybrid" /><Row icon="business-outline" label="Product Manager" value="Razorpay · Bengaluru · Hybrid" /></Card><Card><Text style={s.label}>Why this role fits</Text><Text style={s.detail}>Priya’s payments experience, customer empathy and product scale align strongly with the team’s current needs.</Text></Card><Button label="Continue" state="role" /></Page>; }
function Consent(): ReactElement { return <Page title="Confirm consent" subtitle="Priya has approved sharing this verified package."><Card><Row icon="checkmark-circle-outline" label="Resume & work history" status="Approved" value="Only for this Razorpay referral" /><Row icon="checkmark-circle-outline" label="Contact details" status="Approved" value="Visible to recruiting after submission" /></Card><View style={s.notice}><Ionicons color={lightJourney.ink} name="lock-closed-outline" size={22} /><Text style={s.detail}>You can submit only what Priya has consented to share.</Text></View><Button label="Write referral note" state="consent" /></Page>; }
function Note(): ReactElement { return <Page title="Add your referral note" subtitle="Explain why you believe Priya is a strong fit."><Text style={s.fieldLabel}>Your note to the hiring team</Text><View style={s.note}><TextInput accessibilityLabel="Referral note" defaultValue="Priya is an exceptional product leader with deep payments experience. I’ve seen her build high-trust, high-scale products and would strongly recommend her for this role." multiline style={s.input} /><Text style={s.count}>156/500</Text></View><Card><Text style={s.label}>What gets shared</Text><Text style={s.detail}>Your referral note, Priya’s verified profile, resume and contact details with her approval.</Text></Card><Button label="Review & submit" state="note" /></Page>; }
function Submitted(): ReactElement { return <Page title="Referral submitted" subtitle="Razorpay has received Priya’s verified referral package."><View style={s.success}><Ionicons color={lightJourney.green} name="checkmark" size={38} /></View><Card><Text style={s.label}>Senior Product Manager</Text><Text style={s.detail}>Razorpay · Bengaluru</Text><View style={s.divider} /><Text style={s.detail}>Submitted 19 Jun 2026 · 10:42 AM</Text><Text style={s.detail}>Reference: END-RZP-061926</Text></Card><View style={s.notice}><Ionicons color={lightJourney.ink} name="time-outline" size={22} /><Text style={s.detail}>The recruiting team will review Priya’s package next. We’ll keep you both updated.</Text></View><Button label="Track candidate" state="submitted" /></Page>; }
function Page({ children, subtitle, title }: { children: ReactElement | ReactElement[]; subtitle: string; title: string }): ReactElement { return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text accessibilityRole="header" style={s.title}>{title}</Text><Text style={s.subtitle}>{subtitle}</Text>{children}</ScrollView>; }
function Body({ state }: Props): ReactElement { if(state==='details')return <Details/>; if(state==='received')return <Received/>; if(state==='role')return <Role/>; if(state==='consent')return <Consent/>; if(state==='note')return <Note/>; return <Submitted/>; }
export function EndorserReferralScreen({ state }: Props): ReactElement { return <SafeAreaView edges={['top','left','right']} style={s.safe}><Header /><Body state={state}/></SafeAreaView>; }

const s=StyleSheet.create({safe:{backgroundColor:lightJourney.background,flex:1},header:{alignItems:'center',flexDirection:'row',height:56,justifyContent:'space-between',paddingHorizontal:18},icon:{alignItems:'center',height:44,justifyContent:'center',width:44},wordmark:{color:lightJourney.ink,fontFamily:'IBMPlexSerif-Medium',fontSize:27},content:{flexGrow:1,padding:20},title:{color:lightJourney.ink,fontFamily:'IBMPlexSerif-Medium',fontSize:27,lineHeight:33},subtitle:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:11,lineHeight:17,marginTop:5},card:{backgroundColor:lightJourney.surface,borderColor:lightJourney.border,borderRadius:11,borderWidth:1,marginTop:18,overflow:'hidden',padding:12},row:{alignItems:'center',borderBottomColor:lightJourney.border,borderBottomWidth:1,flexDirection:'row',gap:10,minHeight:59},flex:{flex:1},label:{color:lightJourney.text,fontFamily:'TikTokSans-Medium',fontSize:12},detail:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:10,lineHeight:16,marginTop:3},verified:{color:lightJourney.green,fontFamily:'TikTokSans-Medium',fontSize:10},pending:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:10},primary:{alignItems:'center',backgroundColor:lightJourney.blue,borderRadius:14,height:52,justifyContent:'center',marginTop:20},primaryText:{color:'#FFFFFF',fontFamily:'TikTokSans-Semibold',fontSize:15},success:{alignItems:'center',alignSelf:'center',backgroundColor:lightJourney.greenSoft,borderColor:lightJourney.green,borderRadius:38,borderWidth:2,height:76,justifyContent:'center',marginTop:23,width:76},notice:{alignItems:'center',backgroundColor:lightJourney.surfaceMuted,borderRadius:10,flexDirection:'row',gap:10,marginTop:16,padding:13},divider:{backgroundColor:lightJourney.border,height:1,marginVertical:10},fieldLabel:{color:lightJourney.text,fontFamily:'TikTokSans-Medium',fontSize:11,marginTop:17},note:{backgroundColor:lightJourney.surface,borderColor:lightJourney.border,borderRadius:10,borderWidth:1,marginTop:7,minHeight:160,padding:11},input:{color:lightJourney.text,fontFamily:'TikTokSans-Regular',fontSize:11,lineHeight:17,minHeight:128,textAlignVertical:'top'},count:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:9,textAlign:'right'}});
