import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, router } from 'expo-router';
import type { ReactElement } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { lightJourney } from '../theme/lightJourney';
import { endorserProgressRoute, type EndorserProgressState } from './endorserProgress/endorserProgressModel';

const copy: Record<Exclude<EndorserProgressState, 'list'>, { title: string; detail: string; action: string }> = {
  review: { title: 'Recruiter review', detail: 'Razorpay is reviewing Priya’s verified referral package.', action: 'View application' },
  interview: { title: 'Interview scheduled', detail: 'Priya has an interview with the Razorpay product team.', action: 'See interview details' },
  decision: { title: 'Decision pending', detail: 'The team is consolidating feedback from Priya’s interviews.', action: 'View update' },
  offer: { title: 'Priya received an offer', detail: 'Razorpay has made Priya an offer for Senior Product Manager.', action: 'View offer status' },
  accepted: { title: 'Offer accepted', detail: 'Priya accepted the Razorpay offer. Her joining date is 03 Aug 2026.', action: 'View joining progress' },
  joined: { title: 'Priya joined Razorpay', detail: 'The employment start has been confirmed by Priya.', action: 'Verify employment' },
  verification: { title: 'Verify successful joining', detail: 'Confirm Priya’s start date to complete the referral and unlock your reward.', action: 'Confirm start date' },
};

function Header(): ReactElement { return <View style={s.header}><Pressable accessibilityLabel="Back" accessibilityRole="button" onPress={() => router.back()} style={s.icon}><Ionicons color={lightJourney.ink} name="arrow-back" size={22} /></Pressable><Text style={s.wordmark}>Endorsly</Text><View style={s.icon}><Ionicons color={lightJourney.ink} name="shield-checkmark-outline" size={21}/></View></View>; }
function CandidateCard({ state }: { state: EndorserProgressState }): ReactElement { const active = state === 'list' ? 'review' : state; return <Pressable accessibilityLabel="Priya Nair referral" accessibilityRole="button" onPress={() => router.push(endorserProgressRoute(active) as never)} style={s.card}><View style={s.avatar}><Text style={s.avatarText}>PN</Text></View><View style={s.flex}><Text style={s.name}>Priya Nair</Text><Text style={s.detail}>Senior Product Manager · Razorpay</Text><Text style={s.detail}>{copy[active].title}</Text></View><Ionicons color={lightJourney.textMuted} name="chevron-forward" size={18}/></Pressable>; }
function List(): ReactElement { return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text accessibilityRole="header" style={s.title}>Candidates</Text><Text style={s.subtitle}>Follow every referral you’ve made.</Text><Text style={s.section}>In progress</Text><CandidateCard state="review"/><Text style={s.section}>Completed</Text><View style={s.card}><View style={s.avatar}><Text style={s.avatarText}>NK</Text></View><View style={s.flex}><Text style={s.name}>Neha Kulkarni</Text><Text style={s.detail}>Hired · Reward paid</Text></View></View></ScrollView>; }
function Detail({ state }: { state: Exclude<EndorserProgressState, 'list'> }): ReactElement { const current = copy[state]; const next = state === 'verification' ? '/endorser/earnings/priya-razo/payout' : endorserProgressRoute(nextState(state)); return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.heroIcon}><Ionicons color={state === 'offer' ? lightJourney.orange : lightJourney.green} name={state === 'interview' ? 'calendar-outline' : state === 'verification' ? 'shield-checkmark-outline' : 'checkmark'} size={34}/></View><Text accessibilityRole="header" style={s.title}>{current.title}</Text><Text style={s.subtitle}>{current.detail}</Text><CandidateCard state={state}/><View style={s.timeline}><Text style={s.name}>Referral timeline</Text>{['Matched', 'Referral submitted', 'Recruiter review', 'Interview', 'Decision'].map((item, index) => <View key={item} style={s.timelineRow}><Ionicons color={index < 3 ? lightJourney.green : lightJourney.textMuted} name={index < 3 ? 'checkmark-circle' : 'ellipse-outline'} size={18}/><Text style={s.detail}>{item}</Text></View>)}</View><Pressable accessibilityLabel={current.action} accessibilityRole="button" onPress={() => router.push(next as never)} style={s.primary}><Text style={s.primaryText}>{current.action}</Text></Pressable></ScrollView>; }
function nextState(state: Exclude<EndorserProgressState,'list'>): Exclude<EndorserProgressState,'list'> { const sequence: Exclude<EndorserProgressState,'list'>[]=['review','interview','decision','offer','accepted','joined','verification']; const index=sequence.indexOf(state); return sequence[Math.min(index+1,sequence.length-1)]; }
export function EndorserProgressScreen(): ReactElement { const { stage } = useLocalSearchParams<{stage?: EndorserProgressState}>(); const state = stage && stage !== 'list' ? stage : 'review'; return <SafeAreaView edges={['top','left','right']} style={s.safe}><Header />{stage === undefined ? <Detail state="review"/> : <Detail state={state}/>}</SafeAreaView>; }
export function EndorserCandidateListScreen(): ReactElement { return <SafeAreaView edges={['top','left','right']} style={s.safe}><Header/><List/></SafeAreaView>; }
const s=StyleSheet.create({safe:{backgroundColor:lightJourney.background,flex:1},header:{alignItems:'center',flexDirection:'row',height:56,justifyContent:'space-between',paddingHorizontal:18},icon:{alignItems:'center',height:44,justifyContent:'center',width:44},wordmark:{color:lightJourney.ink,fontFamily:'IBMPlexSerif-Medium',fontSize:27},content:{padding:20},title:{color:lightJourney.ink,fontFamily:'IBMPlexSerif-Medium',fontSize:28,lineHeight:34,marginTop:8},subtitle:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:11,lineHeight:17,marginTop:5},section:{color:lightJourney.ink,fontFamily:'TikTokSans-Medium',fontSize:12,marginTop:22},card:{alignItems:'center',backgroundColor:lightJourney.surface,borderColor:lightJourney.border,borderRadius:11,borderWidth:1,flexDirection:'row',gap:10,marginTop:10,minHeight:76,padding:12},avatar:{alignItems:'center',backgroundColor:lightJourney.blueSoft,borderRadius:25,height:50,justifyContent:'center',width:50},avatarText:{color:lightJourney.ink,fontFamily:'TikTokSans-Medium',fontSize:13},flex:{flex:1},name:{color:lightJourney.text,fontFamily:'TikTokSans-Medium',fontSize:12},detail:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:10,lineHeight:16,marginTop:3},heroIcon:{alignItems:'center',alignSelf:'center',backgroundColor:lightJourney.greenSoft,borderColor:lightJourney.green,borderRadius:37,borderWidth:2,height:74,justifyContent:'center',marginTop:17,width:74},timeline:{backgroundColor:lightJourney.surface,borderColor:lightJourney.border,borderRadius:11,borderWidth:1,marginTop:16,padding:13},timelineRow:{alignItems:'center',flexDirection:'row',gap:9,marginTop:11},primary:{alignItems:'center',backgroundColor:lightJourney.blue,borderRadius:14,height:52,justifyContent:'center',marginTop:20},primaryText:{color:'#FFFFFF',fontFamily:'TikTokSans-Semibold',fontSize:15}});
