import { useState, type ReactElement } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { lightJourney } from '../theme/lightJourney';
import type { InterviewState } from './interview/interviewModel';

export function InterviewScreen({ state }: { state: InterviewState }): ReactElement {
  return <SafeAreaView edges={['top', 'left', 'right']} style={s.safe}><Header /><ScrollView contentContainerStyle={s.content}>{state === 'review' ? <Review /> : state === 'invitation' ? <Invitation /> : state === 'time' ? <Time /> : <Preparation />}</ScrollView></SafeAreaView>;
}

function Header(): ReactElement { return <View style={s.header}><Pressable accessibilityLabel="Back" onPress={() => router.back()} style={s.icon}><Ionicons name="arrow-back" size={22} color={lightJourney.ink} /></Pressable><Text style={s.wordmark}>Endorsly</Text><View style={s.icon}><Ionicons name="shield-checkmark-outline" size={22} color={lightJourney.ink} /></View></View>; }
function Button({ label, path }: { label: string; path: string }): ReactElement { return <Pressable accessibilityLabel={label} onPress={() => router.push(path as never)} style={s.primary}><Text style={s.primaryText}>{label}</Text></Pressable>; }
function Review(): ReactElement { return <><Text style={s.hero}>Referral submitted</Text><Text style={s.copy}>by Arjun on 19 Jun 2026</Text><View style={s.vertical}>{['Referral submitted','Recruiter review','Interview','Outcome'].map((item,index)=><View key={item} style={s.step}><View style={[s.dot,index===0&&s.done,index===1&&s.active]} /><View><Text style={index===1?s.activeText:s.title}>{item}</Text><Text style={s.copy}>{index===0?'19 Jun 2026':index===1?'Started 22 Jun 2026 · The recruiter is reviewing your application and profile.':'Scheduled'}</Text></View></View>)}</View></>; }
function Invitation(): ReactElement { return <><Text style={s.hero}>Razorpay would{`\n`}like to meet you.</Text><Text style={s.copy}>You’re invited for a product interview for Senior Product Manager.</Text><View style={s.card}>{[['Type','Product interview'],['Duration','60 minutes'],['Proposed date','08 Jul 2026'],['Interviewers','Arjun and team']].map(([a,b])=><View key={a} style={s.row}><Text style={s.copy}>{a}</Text><Text style={s.value}>{b}</Text></View>)}</View><View style={s.notice}><Text style={s.title}>♡  This is a human step</Text><Text style={s.copy}>We build technology to bring people closer. Interviews help us learn together.</Text></View><Button label="Choose a time" path="/application/razorpay-spm/interview/time" /><Text style={s.link}>Decline interview</Text></>; }
function Time(): ReactElement { const [chosen,setChosen]=useState('10:30 AM – 11:30 AM');return <><Text style={s.hero}>Choose a time that{`\n`}works for you</Text><Text style={s.copy}>All times in India Standard Time (IST)</Text><Text style={s.date}>▣  Tuesday, 08 Jul 2026</Text>{['09:00 AM – 10:00 AM','10:30 AM – 11:30 AM','02:00 PM – 03:00 PM'].map(item=><Pressable accessibilityRole="radio" accessibilityState={{checked:chosen===item}} key={item} onPress={()=>setChosen(item)} style={[s.slot,chosen===item&&s.slotSelected]}><Text style={chosen===item?s.activeText:s.value}>{item}</Text><Text style={chosen===item?s.activeText:s.copy}>{chosen===item?'●':'○'}</Text></Pressable>)}<View style={s.notice}><Text style={s.title}>▣  Calendar conflict</Text><Text style={s.copy}>You have another event at 11:00 AM. Your 11:30 AM slot may be tight.</Text></View><Button label="Confirm interview" path="/application/razorpay-spm/interview/prep" /></>; }
function Preparation(): ReactElement { return <><Text style={s.hero}>Prepare with{`\n`}confidence.</Text><Text style={s.copy}>Everything you need for your interview with Razorpay.</Text><Card title="Role brief" text="Senior Product Manager at Razorpay" /><Card title="Advice from Arjun" text="Think user outcomes, simplify complex flows, and quantify business impact." /><Card title="Your resume" text="Priya_Nair_Resume_v3.pdf · Uploaded on 18 Jun 2026" /><Card title="Product case preparation" text="Understand Razorpay · Review product case examples · Practice product case · Prepare questions to ask" /><Button label="Continue preparing" path="/application/razorpay-spm" /></>; }
function Card({ title, text }: { title: string; text: string }): ReactElement { return <View style={s.card}><Text style={s.title}>{title}</Text><Text style={s.copy}>{text}</Text></View>; }
const s=StyleSheet.create({safe:{backgroundColor:lightJourney.background,flex:1},header:{alignItems:'center',flexDirection:'row',height:56,justifyContent:'space-between',paddingHorizontal:18},icon:{alignItems:'center',height:44,justifyContent:'center',width:44},wordmark:{color:lightJourney.ink,fontFamily:'IBMPlexSerif-Medium',fontSize:27},content:{padding:20},hero:{color:lightJourney.ink,fontFamily:'IBMPlexSerif-Medium',fontSize:28,lineHeight:34,marginTop:14},copy:{color:lightJourney.textMuted,fontFamily:'TikTokSans-Regular',fontSize:11,lineHeight:17,marginTop:6},vertical:{borderLeftColor:lightJourney.border,borderLeftWidth:1,marginLeft:10,marginTop:26,paddingLeft:20},step:{alignItems:'flex-start',flexDirection:'row',gap:12,minHeight:88},dot:{backgroundColor:lightJourney.background,borderColor:lightJourney.border,borderRadius:11,borderWidth:1,height:22,left:-32,width:22},done:{backgroundColor:lightJourney.green,borderColor:lightJourney.green},active:{borderColor:lightJourney.blue,borderWidth:3},title:{color:lightJourney.ink,fontFamily:'TikTokSans-Medium',fontSize:13},activeText:{color:lightJourney.blue,fontFamily:'TikTokSans-Medium',fontSize:13},card:{backgroundColor:lightJourney.surface,borderColor:lightJourney.border,borderRadius:11,borderWidth:1,marginTop:16,padding:13},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:7},value:{color:lightJourney.text,fontFamily:'TikTokSans-Regular',fontSize:11,maxWidth:'55%',textAlign:'right'},notice:{backgroundColor:lightJourney.surfaceMuted,borderColor:lightJourney.border,borderRadius:10,borderWidth:1,marginTop:18,padding:13},primary:{alignItems:'center',backgroundColor:lightJourney.blue,borderRadius:14,height:51,justifyContent:'center',marginTop:20},primaryText:{color:'#fff',fontFamily:'TikTokSans-Semibold',fontSize:15},link:{color:lightJourney.blue,fontFamily:'TikTokSans-Medium',fontSize:12,marginTop:14,textAlign:'center'},date:{color:lightJourney.text,fontFamily:'TikTokSans-Medium',fontSize:12,marginTop:25},slot:{alignItems:'center',backgroundColor:lightJourney.surface,borderColor:lightJourney.border,borderRadius:10,borderWidth:1,flexDirection:'row',height:50,justifyContent:'space-between',marginTop:9,paddingHorizontal:13},slotSelected:{borderColor:lightJourney.blue,borderWidth:1.5}});
