import { Platform, StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { layout, spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

const RADIUS_LG = 20;
const RADIUS_SM = 6;

export const chatStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: 'transparent' },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  kav: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    paddingHorizontal: layout.screenPaddingH,
    paddingTop: spacing[3],
    paddingBottom: spacing[4],
  },
  backBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -spacing[2],
  },
  headerProfile: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
  },
  headerMeta: { flex: 1, gap: 2 },
  headerName: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 16,
    color: colors.text,
    letterSpacing: 0,
  },
  headerSub: { ...typography.caption, color: colors.textSecondary },
  typingInline: { color: colors.accent },
  chatPanel: {
    flex: 1,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    overflow: 'hidden',
  },
  messageViewport: { flex: 1 },
  messageList: {
    paddingHorizontal: spacing[4],
    paddingTop: spacing[5],
    paddingBottom: spacing[5],
    gap: spacing[4],
  },
  messageSkeletonWrap: {
    gap: spacing[4],
  },
  skeletonTheirs: {
    alignItems: 'flex-start',
    gap: spacing[1],
  },
  skeletonMine: {
    alignItems: 'flex-end',
    gap: spacing[1],
  },
  groupWrap: { maxWidth: '82%' },
  groupMine: { alignSelf: 'flex-end', alignItems: 'flex-end' },
  groupTheirs: { alignSelf: 'flex-start', alignItems: 'flex-start' },
  groupMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing[1],
    paddingHorizontal: spacing[1],
  },
  groupMetaMine: { alignSelf: 'flex-end' },
  groupTime: {
    fontFamily: 'JetBrainsMono-Regular',
    fontSize: 10,
    color: colors.textTertiary,
  },
  bubble: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: RADIUS_LG,
  },
  bubbleText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 15,
    lineHeight: 21,
  },
  textMine: { color: colors.background },
  textTheirs: { color: colors.text },
  bubbleMine: { backgroundColor: colors.accent, borderBottomRightRadius: RADIUS_SM },
  bubbleMineFirst: { borderBottomRightRadius: RADIUS_SM },
  bubbleMineMiddle: {
    borderTopRightRadius: RADIUS_SM,
    borderBottomRightRadius: RADIUS_SM,
  },
  bubbleMineLast: {
    borderTopRightRadius: RADIUS_SM,
    borderBottomRightRadius: RADIUS_SM,
  },
  bubbleTheirs: {
    backgroundColor: colors.surfaceLevel2,
    borderBottomLeftRadius: RADIUS_SM,
  },
  bubbleTheirsFirst: { borderBottomLeftRadius: RADIUS_SM },
  bubbleTheirsMiddle: {
    borderTopLeftRadius: RADIUS_SM,
    borderBottomLeftRadius: RADIUS_SM,
  },
  bubbleTheirsLast: {
    borderTopLeftRadius: RADIUS_SM,
    borderBottomLeftRadius: RADIUS_SM,
  },
  reactionRow: {
    marginTop: -8,
    flexDirection: 'row',
    backgroundColor: colors.backgroundElevated,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  reactionRowMine: { marginRight: 12 },
  reactionRowTheirs: { marginLeft: 12 },
  reactionBadgeText: { fontSize: 12, marginHorizontal: 1 },
  reactionBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reactionPicker: {
    flexDirection: 'row',
    backgroundColor: colors.backgroundElevated,
    borderRadius: 999,
    padding: spacing[2],
    gap: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reactionBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reactionBtnPressed: { backgroundColor: colors.surfaceHover },
  reactionEmoji: { fontSize: 24 },
  systemRow: { alignItems: 'center', marginVertical: spacing[2] },
  systemPill: {
    backgroundColor: colors.surfaceLevel1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[1.5],
  },
  systemText: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 11,
    color: colors.textSecondary,
    letterSpacing: 0,
  },
  typingRow: { alignItems: 'flex-start', marginTop: spacing[2] },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.surfaceLevel2,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: RADIUS_LG,
    borderBottomLeftRadius: RADIUS_SM,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.textSecondary,
  },
  quickRow: {
    paddingTop: spacing[2.5],
    paddingBottom: spacing[2.5],
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: 'rgba(0, 0, 0, 0.10)',
  },
  quickScroll: { paddingHorizontal: spacing[3], gap: spacing[2] },
  quickChip: {
    minHeight: 44,
    justifyContent: 'center',
    backgroundColor: colors.backgroundElevated,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: 999,
    marginRight: spacing[2],
  },
  quickChipText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 13,
    color: colors.text,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing[2],
    paddingHorizontal: spacing[3],
    paddingTop: spacing[2],
    paddingBottom: Platform.OS === 'ios' ? spacing[3] : spacing[3],
    backgroundColor: 'rgba(0, 0, 0, 0.16)',
  },
  inputWrap: {
    flex: 1,
    backgroundColor: colors.surfaceLevel1,
    borderRadius: 22,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    maxHeight: 120,
    minHeight: 44,
    justifyContent: 'center',
  },
  input: {
    fontFamily: 'Outfit-Regular',
    fontSize: 15,
    color: colors.text,
    lineHeight: 20,
    paddingTop: 0,
    paddingBottom: 0,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: { backgroundColor: colors.accentDim },
});
