import { StyleSheet } from 'react-native';

import { colors } from '../../theme/colors';
import { layout, spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

const RADIUS_LG = 20;
const RADIUS_SM = 6;

export const chatStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: 'transparent' },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  kav: { flex: 1 },
  headerShell: {
    paddingHorizontal: layout.screenPaddingH,
    paddingBottom: spacing[2.5],
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceLevel1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.97 }],
  },
  headerMeta: { flex: 1, gap: 3 },
  headerNameRow: {
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  headerName: {
    flex: 1,
    fontFamily: 'Outfit-SemiBold',
    fontSize: 17,
    color: colors.text,
    letterSpacing: 0,
  },
  headerSub: { ...typography.caption, color: colors.textSecondary },
  typingInline: { color: colors.accent },
  stageBadge: {
    borderRadius: 999,
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
    backgroundColor: colors.goldGlow,
    borderWidth: 1,
    borderColor: colors.goldDim,
  },
  stageBadgeText: {
    fontFamily: 'JetBrainsMono-Medium',
    fontSize: 9,
    color: colors.goldBright,
    letterSpacing: 0.4,
  },
  stagePanel: {
    marginTop: spacing[2.5],
    gap: spacing[2],
    padding: spacing[2.5],
    borderRadius: 16,
    backgroundColor: colors.surfaceLevel1,
    borderWidth: 1,
    borderColor: colors.border,
  },
  stageRail: {
    flexDirection: 'row',
    gap: spacing[2],
  },
  stageStep: {
    flex: 1,
    gap: spacing[1.5],
  },
  stageSegment: {
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.surfaceInset,
    borderWidth: 1,
    borderColor: colors.border,
  },
  stageSegmentComplete: {
    backgroundColor: colors.goldDim,
    borderColor: colors.goldDim,
  },
  stageSegmentActive: {
    backgroundColor: colors.goldBright,
    borderColor: colors.goldBright,
    shadowColor: colors.gold,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 4,
  },
  stageStepText: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 10,
    color: colors.textTertiary,
    textAlign: 'center',
  },
  stageStepTextComplete: { color: colors.gold },
  stageStepTextActive: { color: colors.text },
  stagePanelFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
  },
  stagePanelCopy: { flex: 1, minWidth: 0 },
  stagePanelText: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 13,
    color: colors.text,
  },
  stagePanelMeta: {
    marginTop: 1,
    fontFamily: 'Outfit-Regular',
    fontSize: 11,
    color: colors.textTertiary,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    maxWidth: 150,
    minHeight: 36,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1.5],
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  actionBtnText: {
    flexShrink: 1,
    fontFamily: 'Outfit-SemiBold',
    fontSize: 12,
    color: colors.background,
  },
  messageViewport: { flex: 1 },
  messageList: {
    flexGrow: 1,
    justifyContent: 'flex-end',
    padding: layout.screenPaddingH,
    paddingTop: spacing[4],
    gap: spacing[4],
  },
  groupWrap: { maxWidth: '82%' },
  groupMine: { alignSelf: 'flex-end', alignItems: 'flex-end' },
  groupTheirs: { alignSelf: 'flex-start', alignItems: 'flex-start' },
  groupMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing[1],
    paddingHorizontal: spacing[1],
  },
  groupMetaMine: { alignSelf: 'flex-end' },
  groupTime: {
    fontFamily: 'JetBrainsMono-Regular',
    fontSize: 10,
    color: colors.textTertiary,
  },
  bubble: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: RADIUS_LG,
  },
  bubbleText: {
    fontFamily: 'Outfit-Regular',
    fontSize: 15,
    lineHeight: 21,
  },
  textMine: { color: colors.background },
  textTheirs: { color: colors.text },
  bubbleMine: { backgroundColor: colors.accent, borderBottomRightRadius: RADIUS_SM },
  bubbleMineFirst: { borderBottomRightRadius: RADIUS_SM },
  bubbleMineMiddle: {
    borderTopRightRadius: RADIUS_SM,
    borderBottomRightRadius: RADIUS_SM,
  },
  bubbleMineLast: {
    borderTopRightRadius: RADIUS_SM,
    borderBottomRightRadius: RADIUS_SM,
  },
  bubbleTheirs: {
    backgroundColor: colors.surfaceLevel2,
    borderBottomLeftRadius: RADIUS_SM,
  },
  bubbleTheirsFirst: { borderBottomLeftRadius: RADIUS_SM },
  bubbleTheirsMiddle: {
    borderTopLeftRadius: RADIUS_SM,
    borderBottomLeftRadius: RADIUS_SM,
  },
  bubbleTheirsLast: {
    borderTopLeftRadius: RADIUS_SM,
    borderBottomLeftRadius: RADIUS_SM,
  },
  reactionRow: {
    marginTop: -8,
    flexDirection: 'row',
    backgroundColor: colors.backgroundElevated,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  reactionRowMine: { marginRight: 12 },
  reactionRowTheirs: { marginLeft: 12 },
  reactionBadgeText: { fontSize: 12, marginHorizontal: 1 },
  reactionBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reactionPicker: {
    flexDirection: 'row',
    backgroundColor: colors.backgroundElevated,
    borderRadius: 999,
    padding: spacing[2],
    gap: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reactionBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reactionBtnPressed: { backgroundColor: colors.surfaceHover },
  reactionEmoji: { fontSize: 24 },
  systemRow: { alignItems: 'center', marginVertical: spacing[2] },
  systemPill: {
    backgroundColor: colors.surfaceLevel1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[1.5],
  },
  systemText: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 11,
    color: colors.textSecondary,
    letterSpacing: 0,
  },
  typingRow: { alignItems: 'flex-start', marginTop: spacing[2] },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.surfaceLevel2,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: RADIUS_LG,
    borderBottomLeftRadius: RADIUS_SM,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.textSecondary,
  },
  quickRow: {
    paddingBottom: spacing[2],
  },
  quickScroll: { gap: spacing[2] },
  quickChip: {
    minHeight: 44,
    justifyContent: 'center',
    backgroundColor: colors.surfaceLevel1,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: 999,
    marginRight: spacing[2],
  },
  quickChipText: {
    fontFamily: 'Outfit-Medium',
    fontSize: 13,
    color: colors.text,
  },
  composerDock: {
    paddingHorizontal: spacing[3],
    paddingTop: spacing[3],
    backgroundColor: colors.backgroundElevated,
    borderTopWidth: 1,
    borderTopColor: colors.borderStrong,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000000',
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -8 },
    elevation: 16,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing[2],
  },
  inputWrap: {
    flex: 1,
    backgroundColor: colors.surfaceInset,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2.5],
    maxHeight: 124,
    minHeight: 48,
  },
  input: {
    minHeight: 26,
    maxHeight: 104,
    fontFamily: 'Outfit-Regular',
    fontSize: 15,
    color: colors.text,
    lineHeight: 20,
    padding: 0,
    paddingTop: 0,
    paddingBottom: 0,
    textAlignVertical: 'top',
  },
  sendBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.gold,
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  sendBtnDisabled: { backgroundColor: colors.accentDim },
});
